# Generated by Django 4.2 on 2023-04-25 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beverage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homebrewbatch',
            name='ingredients',
        ),
        migrations.AlterField(
            model_name='homebrewbatch',
            name='abv',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='homebrewbatch',
            name='bottle_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='homebrewbatch',
            name='final_gravity',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='homebrewbatch',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homebrewbatch',
            name='rack_date',
            field=models.DateField(blank=True),
        ),
    ]
