# Generated by Django 4.2 on 2023-04-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beverage', '0002_remove_homebrewbatch_ingredients_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.RemoveField(
            model_name='homebrewbatch',
            name='image',
        ),
        migrations.AlterField(
            model_name='homebrewbatch',
            name='original_gravity',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='homebrewbatch',
            name='start_date',
            field=models.DateField(blank=True),
        ),
    ]
